### PR TITLE
Fix issue with resetting AltLoc for new residue

### PR DESCRIPTION
**Pull request by tonyelewis**
This is an attempt to tackle cmbi/xssp#79

Here is a suggested fix. I think this does fix the case in question (residue 124 of 1sx2) but I haven't tested that it doesn't introduce any regressions. Do you have any test resources available? If so, please do apply them.

### CODE REVIEW

**Comment by cbaakman** [comment]
I like this fix, just want a second opinion.

**Comment by tonyelewis** [comment]
No problem - I'm not at all attached to this particular fix's approach :smiley:.

I was aiming for a fairly light, non-intrusive fix. That said, I should perhaps highlight that I've simplified the logic in this condition:
~~~~~.cpp
if (prevAtom
    &&
    (
      atom.mChainID != prevAtom->mChainID
      ||
      atom.mResSeq  != prevAtom->mResSeq
      ||
      atom.mICode   != prevAtom->mICode
    )
  )
~~~~~
...so that may warrant particular attention.

**Comment by jonblack** [comment]
I feel uncomfortable merging this without some tests to ensure there are no regressions. I'd also like to see a test case for the issue the fix resolves.

**Comment by tonyelewis** [comment]
OK. I've put a stripped-down version of the problem PDB in a [comment](https://github.com/cmbi/xssp/issues/79#issuecomment-265717687) on the original issue #79.

Do you have a test framework to which I could add that testcase?

What sort of other tests would you like and where can they be added?

**Comment by tonyelewis** [comment]
For information, here is the DSSP file for 1sx2 before and after the change:
 * [1sx2.dssp.before.txt](https://github.com/cmbi/xssp/files/644338/1sx2.dssp.before.txt)
 * [1sx2.dssp.after.txt](https://github.com/cmbi/xssp/files/644339/1sx2.dssp.after.txt)

From what I can see from a quick look using a decent diff tool, the differences look to be plausibly explicable with the insertion of a missing residue, eg changes to:

 * totals
 * indexes for residues after the inserted residue
 * accessibility in the residue's region
 * angles for the following residue

**Comment by tonyelewis** [comment]
I've run the two versions of the code across all a full snapshot of the PDB from 1st January 2015. For the 108,399 files, both versions generated 105,093 DSSP files. The amended version produced non-identical output for 29 (0.028%) of those (1jxt, 1jxw, 1jxx, 1jxy, 1pq8, 1sx2, 1uwp, 3adm, 3f6w, 3f9s, 3gi0, 3gsg, 3ikw, 3l8l, 3n3m, 3pi7, 3qdc, 3qm9, 3sil, 3toa, 3ukh, 4b6a, 4c68, 4e3l, 4g78, 4kjl, 4kz5, 4p2l and 4q6k).

Here's an archive of both DSSP files for those 29 PDBs : [changed_dssps.tar.gz](https://github.com/cmbi/xssp/files/644481/changed_dssps.tar.gz)

In some of these cases, the proposed fix restores more residues than in 1sx2 (eg, 4 residues in 3f9s, the whole of chain E in 3adm).

**Comment by jonblack** [comment]
In answer to your first question, we use the Boost.Test unit test framework, although we only have one test since the original author didn't provide any and we've made limited changes since taking over.

The manual test you ran is nice and that fills me with a lot more confidence. This reduces the number of automated tests we need and gives us focus.  I recommend writing a few unit tests for the `ReadPDB` function: one for the old scenario that works, one for the new scenario that should now work, and one (perhaps more - depending on whether they are regressions or not) to cover the differences between the old version and the new.

The question on my mind is whether those differences are bugs or not. @cbaakman can you take a look at the differences for those 29 entries and find out whether this is an introduced bug?

**Comment by cbaakman** [comment]
Doesn't look like a bug to me. The accessible surface an hydrogen bond values have changed, but only a little. Some of the angles have changed, but only around the chain break that changed. Also the numbering changes don't matter, since the original pdb numbers are preserved.

**Comment by tonyelewis** [comment]
Thanks for this. I've now added `MProtein::ReadPDB` unit tests to this PR.

**Comment by tonyelewis** [comment]
I've attempted to fix this PR so it merges cleanly into master again after Coos' fd61ba9fb3ba75d1540b2291b1940b8d3afca668.

I'm afraid that's generated a rather messy history, so you may wish to squash the commits if/when merging.

Also worth mentioning: I'd previously added my tests into a shared test program with the existing fasta test but since Coos has gone for more fully splitting out tests, I have done the same with mine.

**Comment by tonyelewis** [comment]
I've tidied up my branch's history (and force-pushed the changes to my repo) so this pull-request's history is a lot tidier now.

So now, AFAIU:
 * the PR merges cleanly
 * the PR's history is clean
 * we've assessed the effects of the change
 * these effects only involve output changes for 29 out of 105,093 PDBs (~0.028%)
 * Coos [is content with these output changes](https://github.com/cmbi/xssp/pull/80#issuecomment-266389980)
 * there are unit tests for the change, including one that's made to pass by the change.

Is anything else required for this PR to be merged?

**Comment by jonblack** [comment]
I'd prefer a single test executable, or one per binary, but that's a minor issue. Everything else looks good. Thanks @tonyelewis.

**Comment by tonyelewis** [comment]
NP. Thanks for this.

**Pull request merged**
